import '../models/component_model.dart';
import '../models/wire_connection.dart';

class SpiceCompiler {
  static String compileNetlist(List<ComponentModel> components, List<WireConnection> wires) {
    StringBuffer sb = StringBuffer();
    sb.writeln("* Audio EDA Generative Netlist");
    sb.writeln("* Auto-generated by Flutter Web UI Canvas");
    sb.writeln("");

    // A dictionary holding the node resolution for each terminal ID.
    Map<String, int> terminalNodeMap = {};
    int nodeCounter = 1;

    // 1. Assign GND nodes strictly to 0.
    for (var comp in components) {
      if (comp.type == ComponentType.ground) {
        for (var term in comp.terminals) {
          terminalNodeMap[term.id] = 0;
        }
      }
    }

    // Helper: Gets existing node or increment new ones for dangling pins.
    int getOrCreateNode(String terminalId) {
      if (!terminalNodeMap.containsKey(terminalId)) {
        terminalNodeMap[terminalId] = nodeCounter++;
      }
      return terminalNodeMap[terminalId]!;
    }

    // 2. Map wires: In a full app, a Union-Find algorithm connects all interconnected wires into a single SPICE Node integer.
    // For this UI mockup MVP, we just assign matching IDs.
    for (var wire in wires) {
      int node = getOrCreateNode(wire.startTerminalId);
      terminalNodeMap[wire.endTerminalId] = node;
    }

    // 3. Generate SPICE text lines per component
    for (var comp in components) {
      if (comp.type == ComponentType.ground) continue;
      
      String line = comp.logicalName;
      // Append generated Netlist Nodes order based on terminal placement constraints
      for (var t in comp.terminals) {
         int node = getOrCreateNode(t.id);
         line += " $node";
      }
      
      // Append literal value
      String val = comp.spiceValue.isEmpty ? "1k" : comp.spiceValue;
      line += " $val";
      
      sb.writeln(line);
    }
    
    return sb.toString();
  }
}
